name: event_ship
description: "Event bus for flutter"
version: 1.0.0
homepage: https://github.com/ENUUI

environment:
  sdk: '>=3.2.3 <4.0.0'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
dev_dependencies:
  build_runner: ^2.4.8
  mockito: ^5.4.4
  test: ^1.25.2
